version: "3.8"
services:
  mongo:
    container_name: "mongo"
    image: mongo:latest
    ports:
      - 27017:27017
  rabbitmq3:
    container_name: "rabbitmq"
    image: rabbitmq:latest
    ports:
      - 5672:5672
      - 15672:15672
