apiVersion: v1
kind: Service
metadata:
  name: $SERVICE_NAME
  labels:
    app: $SERVICE_NAME
spec:
  ports:
  - port: $PORT
    targetPort: $PORT
  selector:
    app: $SERVICE_NAME
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: $SERVICE_NAME
spec:
  replicas: $REPLICAS
  selector:
    matchLabels:
      app: $SERVICE_NAME
  template:
    metadata:
      labels:
        app: $SERVICE_NAME
      annotations:
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/role: 'internal-app'
        vault.hashicorp.com/agent-pre-populate-only : "true"
        vault.hashicorp.com/agent-inject-secret-service: 'internal/data/$ENV_NAME/$SERVICE_NAME'
        vault.hashicorp.com/agent-inject-template-service: |
          {{- with secret "internal/data/$ENV_NAME/$SERVICE_NAME" -}}
            {{- range $key, $value := .Data.data }}
            export {{ $key }}={{ $value }}
            {{- end }}
          {{- end }}
        vault.hashicorp.com/agent-inject-secret-shared: 'internal/data/$ENV_NAME/myc2'
        vault.hashicorp.com/agent-inject-template-shared: |
          {{- with secret "internal/data/$ENV_NAME/myc2" -}}
            {{- range $key, $value := .Data.data }}
            export {{ $key }}={{ $value }}
            {{- end }}
          {{- end }}
    spec:
      serviceAccountName: internal-app
      containers:
        - name: $SERVICE_NAME
          image: $IMAGE_NAME
          args: ["sh", "-c", "for value in /vault/secrets/*; do . $value; done && yarn start"]
          imagePullPolicy: IfNotPresent
          env:
            - name: SERVER_PORT
              value: "$PORT"
      imagePullSecrets:
        - name: myc2-docker-registry
